runtime: nodejs10

instance_class: F2

env_variables:
  DB_NAME: reqwise
  DB_USERNAME: postgres
  DB_PASS: "4MXc5(_inRsJV54J$Ac5"
  DB_HOST: "database-dev-1.cr0vlp9alyoi.us-east-2.rds.amazonaws.com"
  DB_PORT: 5432
  JWT_KEY: "@lVxVTh)^8A6X7))myL4"
  HASHID_KEY: "TQE^6q^ncmeL)31s"

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
