name: Quality assurance

on:
  push:
    branches:
      - "**"

jobs:
  lint-check-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: "10"
      - name: Lint client and check licenses
        working-directory: ./client
        run: |
          npm install
          npm run lint
          npm run licenseChecker
      - name: Lint server and check licenses
        working-directory: ./server
        run: |
          npm install
          npm run lint
          npm run licenseChecker
  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: "10"
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "11"
          postgresql db: "reqwise"
          postgresql user: "postgres"
          postgresql password: "1234"
      - name: Install server dependencies and seed database
        working-directory: ./server
        run: |
          npm install
          npm run seed
        env:
          KNEXMODE: dev
      - name: Install client dependencies
        working-directory: ./client
        run: |
          npm install
      - uses: cypress-io/github-action@v2
        with:
          start: npm run runFullStack
          wait-on: "http://localhost:3000/"
          wait-on-timeout: 120
          working-directory: ./client
        env:
          API_URL: http://localhost:3001
          CYPRESS_DEFAULT_COMMAND_TIMEOUT: ${{secrets.CYPRESS_DEFAULT_COMMAND_TIMEOUT}}
          REQWISE_SLACK_SCOPES: ${{secrets.REQWISE_SLACK_SCOPES}}
          REQWISE_SLACK_CLIENT_ID: ${{secrets.REQWISE_SLACK_CLIENT_ID}}
          REQWISE_SLACK_CLIENT_SECRET: ${{secrets.REQWISE_SLACK_CLIENT_SECRET}}
          JWT_KEY: ${{secrets.JWT_KEY}}
          HASHID_KEY: ${{secrets.HASHID_KEY}}
          KNEXMODE: dev
