name: Quality assurance

on:
  repository_dispatch:
    types: [deploy-completed]
  push:
    branches:
      - "**"
      - "!master"

jobs:
  lint-check-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: "10"
      - name: Lint client and check licenses
        working-directory: ./client
        run: |
          npm install
          npm run lint
          npm run licenseChecker
      - name: Lint server and check licenses
        working-directory: ./server
        run: |
          npm install
          npm run lint
          npm run licenseChecker
  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: "10"
      - name: Install dependencies
        working-directory: ./client
        run: |
          npm install
      - uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: "http://localhost:3000/"
          wait-on-timeout: 120
          working-directory: ./client
        env:
          API_URL: https://qa-dot-reqwise.uc.r.appspot.com
          CYPRESS_DEFAULT_COMMAND_TIMEOUT: ${{secrets.CYPRESS_DEFAULT_COMMAND_TIMEOUT}}
          REQWISE_SLACK_SCOPES: ${{secrets.REQWISE_SLACK_SCOPES}}
          REQWISE_SLACK_CLIENT_ID: ${{secrets.REQWISE_SLACK_CLIENT_ID}}
