on:
  issue_comment:
    types: [created]
name: Automatic Rebase
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@7cea12ac34ab078fa37e87798d8986185afa7bf2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
