name: Create staging pull request
on:
  push:
    branches:
      - staging
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          PULL_REQUEST_FROM_BRANCH: "staging"
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_REVIEWERS: "rosslh"
          FAIL_ON_ERROR: true
